# Generated by Django 4.0.3 on 2022-03-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_category_tag_product_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
