# Generated by Django 4.0.3 on 2022-03-23 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_remove_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_address',
            new_name='shipping_address',
        ),
    ]
